name: Google Indexing API

on:
  schedule:
    - cron: '0 0 * * *' # Menjalankan setiap hari pada pukul 00:00 UTC
  workflow_dispatch:

jobs:
  indexing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client requests

      - name: Set up Google Cloud credentials
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          echo "${GOOGLE_APPLICATION_CREDENTIALS}" > credentials.json
          export GOOGLE_APPLICATION_CREDENTIALS="credentials.json"

      - name: Submit URLs to Google Indexing API
        run: |
          python submit_to_google_indexing_api.py

